### ISSUE TITLE
Assemble Kubernetes 1.15 Release Team

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/sig-release#545] opened 2019-03-14 17:39 UTC
This is the official issue for assembling the Kubernetes 1.15 Release Team.

Please review the [Release Team Selection Process](https://github.com/kubernetes/sig-release/blob/master/release-team/release-team-selection.md) docs for details on the process and criteria.  

tl;dr the current role chooses their successor, this should happen trasnparently

There may be refinements to the process along the way, but I would like to open this issue to get the ball rolling.

I'll open a companion PR to go along with this issue

/sig release
/area release-team
/milestone v1.15

**Comment by spiffxp** [comment] 2019-03-14 17:43
/assign @spiffxp 
I'll be pinging the v1.14 roles for their selections

/assign @claurence @tpepper 
I've asked @claurence to take the role of Release Lead, and @tpepper to take the role of Release Lead Shadow.  This is not intended to setup Tim to take on v1.16, so I would recommend one additional Release Lead Shadow TBD by whatever process @claurence sees fit.

**Comment by spiffxp** [comment] 2019-03-14 17:47
At this point in the process, we're not looking to identify shadows, solely leads.

**Comment by spiffxp** [comment] 2019-03-14 17:52
/assign @justaugustus 
You've opened the last three of these, if you have opinions or suggestions on how this should proceed.  I may be occupied with getting things out the door as we near the end of the cycle so it would be helpful to have someone not so close to the wire ensure this results in a timely release team

**Comment by claurence** [comment] 2019-03-14 17:56
I'd like to nominate @kacole2 to be enhancements lead for 1.15

**Comment by justaugustus** [comment] 2019-03-14 18:17
@spiffxp -- I'm on it! Release Team HR is my fave :heart_eyes:

**Comment by nikopen** [comment] 2019-03-14 19:37
Happy to nominate Nick Lane @soggiest to lead bug triage for v1.15!

**Comment by amwat** [comment] 2019-03-14 20:08
As discussed in the release team meeting, we'd like to experiment with having a non-googler test infra lead with a confirmed googler co-lead/shadow (who has access to the infrastructure).
To that effect I'd like to nominate @imkin to be the test-infra lead and @Katharine for the co-lead/shadow :)

**Comment by lachie83** [comment] 2019-03-15 03:00
I would like to express interest in the following roles:
- Release team lead shadow
- Enhancements shadow

**Comment by kacole2** [comment] 2019-03-15 03:03
thanks @claurence. Happy to accept and help you make another successful Kubernetes release!

**Comment by justaugustus** [comment] 2019-03-15 03:47
I'd like to +1 @lachie83 as an additional Release Team Lead shadow!

**Comment by nikopen** [comment] 2019-03-15 14:00
Having been part of the release team since v1.12 and triage lead in the last two releases, I'm interested in being a Release Lead Shadow.

**Comment by hoegaarden** [comment] 2019-03-15 15:36
I'd like to nominate Cheryl Fong @Bubblemelon to be release branch management lead for `v1.15`.

**Comment by jimangel** [comment] 2019-03-15 17:23
I'd like to nominate Barnie (@MAKOSCAFEE) to be docs lead for 1.15!

**Comment by mariantalla** [comment] 2019-03-15 17:23
I'd like to nominate @alejandrox1 to be the v1.15 CI signal lead.

**Comment by justaugustus** [comment] 2019-03-16 22:01
The initial PR for the 1.15 Release Team is here: #548 

@claurence -- please approve your shadows and that PR when you have a chance.

@dstrebel / @nwoods3 -- please nominate your successors for Release Notes and Communications Lead, respectively.

**Comment by nwoods3** [comment] 2019-03-18 17:03
I would like to nominate @castrojo for Communications Lead 1.15 and @onlydole @kbarnard10 and I would like to be considered for shadows.

**Comment by dstrebel** [comment] 2019-03-19 15:36
Would like to nominate @onyiny-ang for Release Notes lead for 1.15.

**Comment by claurence** [comment] 2019-03-20 00:28
I'd like to accept @lachie83 @nikopen and @tpepper as Release Lead shadows for 1.15

**Comment by claurence** [comment] 2019-03-20 00:28
and adding in @jberkus who has expressed interest in being a Lead for Shadows for 1.15.  This is a new role whose initial responsibilities would be to support shadows, ensure their success and help with shadow selection.

**Comment by jimangel** [comment] 2019-03-22 15:42
After doing docs for the past 3 releases, I'm interested in pushing my comfort zone and being a CI Signal Shadow for 1.15.

**Comment by krmayankk** [comment] 2019-03-26 05:21
i would like to shadow for Enhancements

**Comment by mariantalla** [comment] 2019-03-26 11:38
If there's still space, I'd be interested in shadowing test-infra.

**Comment by craiglpeters** [comment] 2019-03-26 21:10
I'd like to shadow enhancements

**Comment by claurence** [comment] 2019-03-26 21:54
Thanks for all the interest in shadowing!  We will be sending out a survey again similar to what was done in the 1.14 cycle

@spiffxp - given we're doing a survey for shadows do we need to leave this issue open until shadow selection is done or is getting the lead team enough to close this?

**Comment by justaugustus** [comment] 2019-03-26 22:01
Let's keep it open until we either close the books on shadows or post a link to the forthcoming survey.

**Comment by simplytunde** [comment] 2019-03-27 20:03
I am still interested in continuing my role as a doc shadow for 1.15. excited!!!

**Comment by jberkus** [comment] 2019-03-28 22:25
The application from for Shadows is now available!  Please fill it out if you're interested in shadowing.

https://forms.gle/qgyvFABJ3RNH95TDA

@simplytunde @craiglpeters @mariantalla @krmayankk @lachie83

**Comment by Bubblemelon** [comment] 2019-04-08 19:05
@SlickNik would like to continue as a branch management shadow from 1.14 :tada:

**Comment by denisra** [comment] 2019-04-17 21:19
I know I might be a bit late for this release, but I'd like to shadow for the Patch Release Management Team or the Bug Triage if possible.

**Comment by justaugustus** [comment] 2019-05-01 10:50
This is complete! Thanks to everyone who volunteered!
/close

**Closed by justaugustus** 2019-05-01 10:50 UTC
Labels: area/release-team, sig/release

**Comment by dankohn** [comment] 2019-06-10 18:39
On closing, it would be nice to point to https://github.com/kubernetes/sig-release/blob/master/releases/release-1.15/release_team.md for the results.
