### ISSUE TITLE
process docu: release team Features Lead

### ISSUE THREAD

**Issue by tpepper** [kubernetes/sig-release#188] opened 2018-06-19 18:01 UTC
The release team's Features Lead role is only minimally documented in two bullets of text in:
https://github.com/kubernetes/sig-release/blob/master/README.md
with no details in:
https://github.com/kubernetes/sig-release/tree/master/release-process-documentation/release-team-guides 

This role was much more active in the 1.11 release and better coordinated with the docs role.  We should document the role, recent process improvements, and current intended improvements.

**Comment by justaugustus** [comment] 2018-06-19 18:48
@tpepper -- going to close this out as it's a dupe of https://github.com/kubernetes/sig-release/issues/124.
/close

**Closed by justaugustus** 2018-06-19 18:48 UTC
